### ISSUE TITLE
Research solution for faking (or implementing) plugin persistance

### ISSUE THREAD

**Issue by rwaldron** [rwaldron/popcorn.sequence#11]
Currently, if a plugin call persists over >1 clip the plugin's content has to be reset for each clip, this could be done in a way that the reset isn't perceived by the viewer. Alternatively, research a way to possibly persist plugin content over >1 clip without resetting at all.

**Comment by cadecairos** [comment]
I can think of two possible ways to approach this:

Because the sequencer actually plays an extra second of each clip, the end methods of the plug-ins are being called before cycle is called to swap to the next popcorn instance. we'd need to close that gap somehow.

Another consideration is creating a plug-in mechanism for the sequencer itself, which can somehow track the time of the sequence and handle start and end methods of plugins independently from popcorn.

both options will have their pros and cons...

**Comment by rwaldron** [comment]
The sequencer should use the existing plugins or none at all. If we have to provide two paths we've effectively failed. 

The first part sound promising.
